### ISSUE TITLE
AttributeError: module django.urls.resolvers has no attribute RegexURLResolver

### ISSUE THREAD

**Issue by duckduckgrayduck** [MuckRock/muckrock#1900]
Aug 21 14:16:13 [muckrock-staging](https://my.papertrailapp.com/systems/muckrock-staging/events?focus=1762979013393846283&selected=1762979013393846283) [app/scheduler.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.1&focus=1762979013393846283&selected=1762979013393846283) AttributeError: module 'django.urls.resolvers' has no attribute 'RegexURLResolver'

Found in papertrails on Heroku logs from recent heroku stack update

**Comment by duckduckgrayduck** [comment]
Found where they are located:
./src/django-opensearch/opensearch/urls.py:10
./src/django-opensearch/tests/test_views.py:15:from django.urls.resolvers import URLPattern, URLResolver

**Comment by duckduckgrayduck** [comment]
Traceback (most recent call last):
Aug 21 14:27:20 [muckrock-staging](https://my.papertrailapp.com/systems/muckrock-staging/events?focus=1762981807777562641&selected=1762981807777562641) [app/scheduler.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.1&focus=1762981807777562641&selected=1762981807777562641)   File "/app/.heroku/python/lib/python3.9/site-packages/newrelic-[2.70.0.51](https://my.papertrailapp.com/systems/muckrock-staging/events?q=%222.70.0.51%22&focus=1762981807777562641&selected=1762981807777562641)/newrelic/config.py", line 1012, in _instrument
Aug 21 14:27:20 [muckrock-staging](https://my.papertrailapp.com/systems/muckrock-staging/events?focus=1762981807777562642&selected=1762981807777562642) [app/scheduler.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.1&focus=1762981807777562642&selected=1762981807777562642)     getattr(newrelic.api.import_hook.import_module(module),
Aug 21 14:27:20 [muckrock-staging](https://my.papertrailapp.com/systems/muckrock-staging/events?focus=1762981807777562643&selected=1762981807777562643) [app/scheduler.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.1&focus=1762981807777562643&selected=1762981807777562643)   File "/app/.heroku/python/lib/python3.9/site-packages/newrelic-[2.70.0.51](https://my.papertrailapp.com/systems/muckrock-staging/events?q=%222.70.0.51%22&focus=1762981807777562643&selected=1762981807777562643)/newrelic/hooks/framework_django.py", line 622, in instrument_django_core_urlresolvers
Aug 21 14:27:20 [muckrock-staging](https://my.papertrailapp.com/systems/muckrock-staging/events?focus=1762981807777562645&selected=1762981807777562645) [app/scheduler.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.1&focus=1762981807777562645&selected=1762981807777562645)     module.RegexURLResolver.resolve)
Aug 21 14:27:20 [muckrock-staging](https://my.papertrailapp.com/systems/muckrock-staging/events?focus=1762981807777562646&selected=1762981807777562646) [app/scheduler.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.1&focus=1762981807777562646&selected=1762981807777562646) AttributeError: module 'django.urls.resolvers' has no attribute 'RegexURLResolver'

This is also an error from newrelic.
